# Generated by Django 4.2.6 on 2023-11-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercharacter',
            name='character_server',
        ),
        migrations.AddField(
            model_name='usercharacter',
            name='character_server',
            field=models.ManyToManyField(blank=True, to='user.characterserver'),
        ),
    ]
