# Generated by Django 4.2.6 on 2023-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usercharacter_character_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharacter',
            name='maple_api_key',
            field=models.TextField(blank=True),
        ),
    ]
