# Generated by Django 4.2.6 on 2023-11-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usercharacter_maple_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercharacter',
            name='character_img',
            field=models.ImageField(blank=True, upload_to='UserCharacter/images/%Y/%m/%d/', verbose_name='캐릭터 이미지'),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='character_name',
            field=models.TextField(blank=True, verbose_name='캐릭터 이름'),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='character_server',
            field=models.ManyToManyField(blank=True, to='user.characterserver', verbose_name='캐릭터 서버'),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='maple_api_key',
            field=models.TextField(blank=True, verbose_name='API 키'),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='profile_word',
            field=models.TextField(blank=True, verbose_name='자기소개'),
        ),
    ]
